defaults:
  - _self_
  - _base_model_config.yaml   # general, model independent, parameters

_target_: src.models.networks_edm.DhariwalUNet
model_channels: 192
channel_mult: [1, 2, 3, 4]
channel_mult_emb: 4
num_blocks: 3
attn_resolutions: [32, 16, 8]
dropout: 0.1
emb_init_identity: False # initialize time embeddings to 0 (no effect as adaLN conditioning)