defaults:
  - adm.yaml   # inherit defaults from adm.yaml
  - _self_

_target_: src.models.networks_edm_new.DhariwalUNet3DTemporal
temporal_op: "attn"
 # use temporal block after first encoder conv or not
init_temporal_op: False
# use temporal block before downsampling or not. If False, use after downsampling.
#  If null, don't use temporal block before or after downsampling
temporal_op_before_down: null
# use temporal block after the last decoder block or not
final_temporal_op: False
causal_attn: False
temporal_kernel_size: 3
use_time_emb_for_temporal_layers: null
extra_time_emb_mlp: False