# --> EDIT the data_dir to the path where the data is stored, if necessary:
# Make sure that ``data_dir`` points to an absolute path!
#   Note: ${oc.env:HOME} is the path to home directory
#   By default, the datamodules can automatically infer if the data is stored in the subdirectories
#             $data_dir/oisstv2   or   $data_dir/physical-nn-benchmark
#   So, if you adhere to this naming, you can keep data_dir to point to their parent dir. By default, ``$HOME/data``
data_dir: "${oc.env:HOME}/data"

# --> Optional edits:
batch_size: 64                 # batch size for training (global over all GPUs. Per-GPU batch size is batch_size // world_size)
batch_size_per_gpu: null       # batch size per GPU (if null, batch_size // world_size is used). If smaller than batch_size, gradient accumulation is used
eval_batch_size: ${datamodule.batch_size} # batch size for validation/testing (larger might be faster, but uses more RAM)

num_workers: "auto"              # number of workers for data loading  (-1 means all available CPUs)
pin_memory: True
prefetch_factor: null
persistent_workers: True
drop_last: False
verbose: ${verbose}

window: 1
# seed_data: 77                # random seed for reproducibility of random data split (different to the one for training)
