defaults:
  - _base_data_config.yaml   # general, dataset-independent, parameters
  - _self_

_target_: src.datamodules.climatebench.climatebench_daily.ClimateBenchDailyDataModule
data_dir: "~/data/climate-analytics-lab-shared/ClimateBench/daily/data"   # Make sure that it is an absolute path!
window: 1 # no window since the granularity is daily (for now)
simulations: ['ssp126', 'ssp370', 'ssp585']
normalize_vars: ['CO2', 'CH4', 'SO2', 'BC']
output_vars: "tas"

sim_validation: 'ssp370'
validation_size: 45
mean_over_ensemble: True
scale_inputs: null #'upscale' # 'upscale' or 'downscale'

# Debugging parameters
DEBUG_dataset_size: 30 # Set to None to use the full dataset, value is the number of years to use
