defaults:
  - era5_base.yaml   # general, dataset-independent, parameters
  - _self_

_target_: src.datamodules.era5.ERA5DataModule3D
variables_3d:
  - "geopotential"
  - "specific_humidity"
  - "temperature"
  - "u_component_of_wind"
  - "v_component_of_wind"
variables_2d:
    - "mean_sea_level_pressure"
    - "10m_u_component_of_wind"
    - "10m_v_component_of_wind"
    - "2m_temperature"
pressure_levels: [50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]