defaults:
  - _self_
  - _base_data_config_temporal.yaml   # general, dataset-independent, parameters

_target_: src.datamodules.physical_systems_benchmark.PhysicalSystemsBenchmarkDataModule
# data_dir: "C:/Users/XYZ/data/physical-nn-benchmark"
physical_system: "navier-stokes"
prediction_horizon: null        # prediction horizon (in days), if null, use the default horizon
num_trajectories: null   # number of trajectories to use (null = all)
