# @package _global_

# to execute this module run:
# python run.py module=rdm

defaults:
  - _base_multi_horizon_config.yaml
  - _self_

module:
  _target_: src.experiment_types.forecasting_multi_horizon.RollingDiffusion
  initialize_window: "regression"
  regression_model: null
  regression_run_id: null
  regression_local_checkpoint_path: True   # automatic search in local dirs
  regression_use_ema: True
  regression_inference_dropout: False

model:
  with_time_emb: False   # no need to embed time for the diffusion model

