# @package _global_

# debug mode sets name of the logging folder to 'logs/debug/...'
# enables trainer debug options
# also sets level od command line logger to DEBUG
# example usage:
# `python run.py mode=debug_era5_ar`

defaults:
  - debug_era5.yaml
  - _self_

# experiment=navier_stokes callbacks=none logger=none datamodule.num_workers=0 datamodule.num_trajectories=1
datamodule:
  output_vars: ${datamodule.input_vars}