# @package _global_

# example usage:
# `python run.py mode=test_spring_mesh logger.wandb.id=SOME_WANDB_ID`

defaults:
  - test.yaml
  - _self_

logger:
  wandb:
    project: "DYffusion-spring-mesh"  # project in wandb of training runs
    project_test: "DYffusion-spring-mesh-TEST"  # overrides logger.wandb.project (allows to use different project for test metrics)


# Checkpoint path to be loaded from wandb cloud (see files tab of run page) or locally (use absolute path)
ckpt_path: "latest_epoch"  # best-val_avg_crps.ckpt"