# @package _global_

defaults:
  - _base_dyffusion.yaml
  - /model@diffusion.interpolator: unet_simple_navier_stokes # how to do sth equivalent to: ${model}
  - _self_


diffusion:
  _target_: src.diffusion.dyffusion_e2e.DYffusionEnd2EndSeparateModels
#  interpolator: ${model}   # does not seem to work?
  lambda_reconstruction: 0.5
  lambda_reconstruction2: 0.0
  lambda_interpolation: 0.25
  lambda_interpolation2: 0.25
  reconstruction2_detach_x_last: False   # True or False
  detach_interpolated_data: False   # True or False
  detach_interpolated_data2: False   # True or False
  interpolator_freeze_start_step: null
  condition_on_x_last: True
  loss_function_interpolation: "mse"
  loss_function_forecast: "mae"
  time_encoding: "discrete"
  refine_predictions: False
  refinement_rounds: 0
  #
  forward_conditioning: "none"
  #
  enable_interpolator_inference_dropout: False

